# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  
  - name: 'Dependencies'
    init: > 
      pip install -r requirements.txt && 
      mkdir /workspace/mlruns && 
      gp sync-done deps
  
  - name: 'MLflow Server'
    init: > 
      gp sync-await deps && 
      gp sync-done server
    command: mlflow server --backend-store-uri sqlite:////workspace/mlruns.db --default-artifact-root /workspace/mlruns

  - name: 'Quarto'
    init: >
      gp sync-await server && 
      wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.2.253/quarto-1.2.253-linux-amd64.deb && 
      sudo dpkg -i quarto-1.2.253-linux-amd64.deb && 
      rm -f quarto-1.2.253-linux-amd64.deb && 
      quarto render .
    command: quarto preview .