# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: 'Set-up Quarto'
    init: | 
      wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.2.253/quarto-1.2.253-linux-amd64.deb
      sudo dpkg -i quarto-1.2.253-linux-amd64.deb
      rm -f quarto-1.2.253-linux-amd64.deb
    command: quarto -V
    
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
