project:
  type: site
  title: "Introduction to MLflow"
  output-dir: ./_site

site:
  title: "Data & AI Engineering Academy"
  
  sidebar:
    style: "floating"
    search: true
    contents:
      - section: "Introduction"
        contents:
          - ml_complexities.ipynb
          - mlflow_intro.ipynb
      - section: "Example"
        contents:
          - mlflow.ipynb
  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true