project:
  type: site
  render: 
    - 01_ml_complexities.ipynb
    - 02_mlflow_intro.ipynb
    - 03_mlflow.ipynb
  title: "Introduction to MLflow"
  output-dir: ./_site

site:
  title: "Data & AI Engineering Academy"
  
  sidebar:
    style: "floating"
    search: true
    contents:
      - section: "Introduction"
        contents:
          - 01_ml_complexities.ipynb
          - 02_mlflow_intro.ipynb
      - section: "Example"
        contents:
          - 03_mlflow.ipynb
  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true