name: Render and deploy Quarto files
on: 
  push:
  pull_request:

jobs:
  quarto-render-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.8"

    - name: "Install Python deps"
      run: |
        pip install -r requirements.txt
        
    - name: "Install Quarto"
      shell: bash
      run: |
        quarto_version="1.2.258"
        quarto_file_name="quarto-${quarto_version}-linux-amd64.deb"
        quarto_url="https://github.com/quarto-dev/quarto-cli/releases/download/v${quarto_version}/${quarto_file_name}"
        wget -q "${quarto_url}"
        sudo dpkg -i "${quarto_file_name}"
    
    - name: "Render Quarto Docs"
      shell: bash
      run: |
        quarto render .

    - name: "Deploy to gh-pages"
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
